### ISSUE TITLE
After create all MEHolo module, select part of modules not work

### ISSUE THREAD

**Issue by sunt89** [DataMesh-OpenSource/METoolkit#1]
Test Unity Version : 5.5.0f3
After create all MEHolo module, select part of modules not work.  

Found `UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());`  not work.
And I change the code `EditorUtility.SetDirty(entrance);` ,It works.

**Comment by playerwu** [comment]
I will put this code into MEHolo module, Thank you!~~
